services:
#    sicem_user.example:
#        class: Sicem\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sicem_user.admin.ctl_user:
        class: Sicem\UserBundle\Admin\CtlUserAdmin
        arguments: [~, Sicem\UserBundle\Entity\CtlUser, SicemUserBundle:CtlUserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Usuarios }
