services:
#    sicem_catalogo.example:
#        class: Sicem\CatalogoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sicem_catalogo.admin.ctl_empresa:
        class: Sicem\CatalogoBundle\Admin\CtlEmpresaAdmin
        arguments: [~, Sicem\CatalogoBundle\Entity\CtlEmpresa, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Empresas }
