services:
#    sicem_catalogo.example:
#        class: Sicem\CatalogoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sicem_catalogo.admin.ctl_empresa:
        class: Sicem\CatalogoBundle\Admin\CtlEmpresaAdmin
        arguments: [~, Sicem\CatalogoBundle\Entity\CtlEmpresa, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CtlEmpresa }

    sicem_catalogo.admin.ctl_contabilidad:
        class: Sicem\CatalogoBundle\Admin\CtlContabilidadAdmin
        arguments: [~, Sicem\CatalogoBundle\Entity\CtlContabilidad, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CtlContabilidad }

    sicem_catalogo.admin.ctl_anio:
        class: Sicem\CatalogoBundle\Admin\CtlAnioAdmin
        arguments: [~, Sicem\CatalogoBundle\Entity\CtlAnio, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CtlAnio }
